import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, Sparkles, Shield, Cloud } from 'lucide-react';

interface FaqItem {
  question: string;
  answer: string;
  category: 'General' | 'Security & API' | 'Deployment' | 'Prompts';
}

const FAQS: FaqItem[] = [
  {
    category: 'General',
    question: 'What is PromptGenius AI?',
    answer:
      'PromptGenius AI is a creator toolkit and AI prompt engineering platform powered by the Gemini API. It transforms simple 1-line ideas into comprehensive, professionally formatted prompts crafted specifically for ChatGPT, Claude 3.7, Midjourney v6, Sora, Runway Gen-3, and developer environments.',
  },
  {
    category: 'General',
    question: 'Can I use the generated prompts commercially?',
    answer:
      'Yes, 100%! All prompts synthesized by PromptGenius AI are your intellectual property to use in client work, commercial advertising campaigns, digital product creation, YouTube videos, and software development with no royalty obligations.',
  },
  {
    category: 'Security & API',
    question: 'Is my Gemini API key secure?',
    answer:
      'Completely secure. PromptGenius AI is engineered with an isolated server-side architecture. In local development or container hosting, requests are proxied via Express backend. When deployed on Netlify, requests are routed through serverless Lambda functions (in /netlify/functions). The browser never sees or downloads your GEMINI_API_KEY.',
  },
  {
    category: 'Security & API',
    question: 'What happens if no API key is set in production?',
    answer:
      'If GEMINI_API_KEY is not configured in the environment, the server-side engine returns a clean, friendly 500 error explaining that the administrator needs to set GEMINI_API_KEY in the Netlify site settings dashboard or local .env file. The application will never crash or hang indefinitely.',
  },
  {
    category: 'Deployment',
    question: 'How do I deploy PromptGenius AI to Netlify?',
    answer:
      '1. Push your code to GitHub, GitLab, or Bitbucket.\n2. In Netlify, click "Add new site" > "Import an existing project".\n3. Set Build command to "npm run build" and Publish directory to "dist".\n4. Under Site Settings > Environment Variables, add GEMINI_API_KEY with your key from Google AI Studio.\n5. Deploy! Netlify automatically mounts the serverless functions in /netlify/functions and redirects /api/* requests per netlify.toml.',
  },
  {
    category: 'Prompts',
    question: 'What AI tools and models are supported?',
    answer:
      'Prompts generated by PromptGenius AI are compatible with all modern generative AI tools:\n• Text & Reasoning: ChatGPT (GPT-4o, o3-mini), Claude (3.7 Sonnet), Google Gemini (2.5 & 3.8 Flash)\n• Image Generation: Midjourney v6, Stable Diffusion 3, Flux.1, Google Imagen 3, DALL-E 3\n• Video Generation: OpenAI Sora, Runway Gen-3 Alpha, Kling AI, Luma Dream Machine, Pika\n• Code Generation: GitHub Copilot, Cursor, Claude Code, Windsurf.',
  },
  {
    category: 'Prompts',
    question: 'How does the "Improve Prompt" feature work?',
    answer:
      'When you click "Improve Prompt", the current prompt is passed to our server-side Gemini intelligence engine with prompt engineering heuristics. Gemini analyzes the instruction clarity, removes ambiguity, enriches camera/lighting/stylistic parameters, and outputs a revised version.',
  },
];

export const FaqView: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const categories = ['All', 'General', 'Prompts', 'Security & API', 'Deployment'];

  const filteredFaqs = FAQS.filter(
    (faq) => selectedCategory === 'All' || faq.category === selectedCategory
  );

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 space-y-8">
      <div className="text-center space-y-2">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 text-xs font-semibold">
          <HelpCircle className="w-3.5 h-3.5" />
          <span>Knowledge & Help Center</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white font-['Outfit']">
          Frequently Asked Questions
        </h1>
        <p className="text-sm sm:text-base text-slate-600 dark:text-slate-400 max-w-xl mx-auto">
          Everything you need to know about prompt optimization, API privacy, and deploying to Netlify.
        </p>
      </div>

      {/* Category Filter Pills */}
      <div className="flex items-center justify-center gap-2 flex-wrap">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all ${
              selectedCategory === cat
                ? 'bg-indigo-600 text-white shadow-xs'
                : 'bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* FAQ Accordion */}
      <div className="space-y-3">
        {filteredFaqs.map((faq, index) => {
          const isOpen = openIndex === index;
          return (
            <div
              key={index}
              className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-xs transition-all"
            >
              <button
                onClick={() => setOpenIndex(isOpen ? null : index)}
                className="w-full px-5 py-4 text-left flex items-center justify-between gap-4 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                aria-expanded={isOpen}
              >
                <span className="text-sm sm:text-base font-bold text-slate-900 dark:text-white font-['Outfit']">
                  {faq.question}
                </span>
                <span className="p-1 rounded-lg text-slate-400 bg-slate-100 dark:bg-slate-800 shrink-0">
                  {isOpen ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </span>
              </button>

              {isOpen && (
                <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed border-t border-slate-100 dark:border-slate-800/80 whitespace-pre-line">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
